DROP DATABASE MOLAB;

CREATE DATABASE MOLAB;
USE MOLAB;

CREATE TABLE USER (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20),
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PHONE_NO VARCHAR(20),
	LEFTTIME INTEGER UNSIGNED NOT NULL,
	STATE TINYINT UNSIGNED NOT NULL,
	ROLE TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
/*
	STATE: 0:actived; 1:unactived; 2:login limited; 3:operation limited
	ROLE: 0:admin; 1:user
*/
INSERT INTO USER VALUES (
	1000000, 'admin', 'admin', 'admin,123', 'admin@xinfuonline.com', '(+86)13866668888', 900, 0, 0
);
INSERT INTO USER VALUES (
	1000001, 'molab', 'molab', 'molab,123', 'molab@xinfuonline.com', '(+86)13866668888', 900, 0, 1
);
INSERT INTO USER VALUES (
	1000002, 'test', '', 'test', 'test@xinfuonline.com', '', 900, 0, 1
);


CREATE TABLE DEVICE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	IMEI VARCHAR(20),
	SERVER VARCHAR(50) NOT NULL,
	SERIALNUMBER VARCHAR(50) NOT NULL,
	MANUFACTURER VARCHAR(20),
	MODEL VARCHAR(20),
	OS VARCHAR(20),
	WIDTH INTEGER UNSIGNED NOT NULL,
	HEIGHT INTEGER UNSIGNED NOT NULL,
	ISEMULATOR TINYINT UNSIGNED NOT NULL,
	STATE TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
INSERT INTO DEVICE VALUES (
	1000000, '000000000000000', 'http://localhost:8081/ATS/', 'emulator-5554', 'Google Inc.', 'Google Inc.', 'Android 2.3.3', 320, 480, 1, 0
);
/*
	ISEMULATOR: 0:false; 1:true
	STATE: 0:free; 1:busy; 2:reserved; 3:unactived
*/

CREATE TABLE RESERVATION (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID INTEGER UNSIGNED NOT NULL,
	DEVICE_ID INTEGER UNSIGNED NOT NULL,
	STARTTIME BIGINT UNSIGNED NOT NULL,
	ENDTIME BIGINT UNSIGNED NOT NULL,
	STATE TINYINT UNSIGNED NOT NULL, /* 0:handled; 1:not handled yet.*/
	PRIMARY KEY (ID),
	INDEX (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	INDEX (DEVICE_ID),
	FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
INSERT INTO RESERVATION VALUES (
	1000000, 1000000, 1000000, 1318690532000, 1318690532000, 0
);

CREATE TABLE PROJECT (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID INTEGER UNSIGNED NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CREATE_TIME BIGINT UNSIGNED,
	MODIFY_TIME BIGINT UNSIGNED,
	PRIMARY KEY (ID),
	INDEX (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
INSERT INTO PROJECT VALUES (
	1000000, 1000000, 'test', 1318688909000, 1318690532000
);

CREATE TABLE TESTCASE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PROJECT_ID INTEGER UNSIGNED NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	TESTCASE BLOB NOT NULL,
	CREATE_TIME BIGINT UNSIGNED,
	MODIFY_TIME BIGINT UNSIGNED,
	PRIMARY KEY (ID),
	INDEX (PROJECT_ID),
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE LOG (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_ID INTEGER UNSIGNED NOT NULL,
	DEVICE_ID INTEGER UNSIGNED,
	OPERATION VARCHAR(50) NOT NULL,
	TIME BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (ID),
	INDEX (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
INSERT INTO LOG VALUES (
	1000000, 1000000, 1000000, 'LOGIN', 1318690532000
);